language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
services:
  - riak
before_script:
  - ./src/riak_setup.sh
# command to run tests
script:
  - coverage run --source='src' src/manage.py test
  - coverage report --omit=*test*,*settings*